export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const FETCH_RESERVATIONS_SUCCESS = 'FETCH_RESERVATIONS_SUCCESS';
export const FETCH_RESERVATIONS_FAILURE = 'FETCH_RESERVATIONS_FAILURE';

export const FETCH_RESERVATIONS_CLIENT = 'FETCH_RESERVATIONS_CLIENT';
export const FETCH_RESERVATIONS_CLIENT_SUCCESS =
  'FETCH_RESERVATIONS_CLIENT_SUCCESS';
export const FETCH_RESERVATIONS_CLIENT_FAILURE =
  'FETCH_RESERVATIONS_CLIENT_FAILURE';

export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const FETCH_SPOTS = 'FETCH_SPOTS';
export const FETCH_SPOTS_SUCCESS = 'FETCH_SPOTS_SUCCESS';
export const FETCH_SPOTS_FAILURE = 'FETCH_SPOTS_FAILURE';

export const CREATE_SPOT = 'CREATE_SPOT';
export const CREATE_SPOT_SUCCESS = 'CREATE_SPOT_SUCCESS';
export const CREATE_SPOT_FAILURE = 'CREATE_SPOT_FAILURE';

export const CREATE_RESERVATION = 'CREATE_RESERVATION';
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAILURE = 'CREATE_RESERVATION_FAILURE';

export const GET_AVAILABLE_SPOTS = 'GET_AVAILABLE_SPOTS';
export const GET_AVAILABLE_SPOTS_SUCCESS = 'GET_AVAILABLE_SPOTS_SUCCESS';
export const GET_AVAILABLE_SPOTS_FAILURE = 'GET_AVAILABLE_SPOTS_FAILURE';

export const CANCEL_RESERVATION = 'CANCEL_RESERVATION';
export const CANCEL_RESERVATION_SUCCESS = 'CANCEL_RESERVATION_SUCCESS';
export const CANCEL_RESERVATION_FAILURE = 'CANCEL_RESERVATION_FAILURE';

export const UPDATE_RESERVATION_MANAGER = 'UPDATE_RESERVATION_MANAGER';
export const UPDATE_RESERVATION_MANAGER_SUCCESS =
  'UPDATE_RESERVATION_MANAGER_SUCCESS';
export const UPDATE_RESERVATION_MANAGER_FAILURE =
  'UPDATE_RESERVATION_MANAGER_FAILURE';

export const UPDATE_SPOT = 'UPDATE_SPOT';
export const UPDATE_SPOT_SUCCESS = 'UPDATE_SPOT_SUCCESS';
export const UPDATE_SPOT_FAILURE = 'UPDATE_SPOT_FAILURE';

export const DELETE_SPOT = 'DELETE_SPOT';
export const DELETE_SPOT_SUCCESS = 'DELETE_SPOT_SUCCESS';
export const DELETE_SPOT_FAILURE = 'DELETE_SPOT_FAILURE';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
